import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from '../models/Product';
import path from 'path';

// Load env vars
dotenv.config({ path: path.join(__dirname, '../../.env') });

const products = [
    {
        id: 'p1',
        name: 'Fresh Organic Bananas',
        description: 'Sweet and ripe organic bananas, perfect for breakfast or snacking',
        price: 45,
        originalPrice: 60,
        image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400',
        category: 'fruits-vegetables',
        stock: 150,
        isAvailable: true,
        isNew: false,
        discount: 25,
        rating: 4.5,
        unit: '1 dozen',
    },
    {
        id: 'p2',
        name: 'Red Apples',
        description: 'Crispy and juicy red apples from Himachal Pradesh',
        price: 180,
        originalPrice: 220,
        image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400',
        category: 'fruits-vegetables',
        stock: 80,
        isAvailable: true,
        discount: 18,
        rating: 4.7,
        unit: '1 kg',
    },
    {
        id: 'p3',
        name: 'Fresh Tomatoes',
        description: 'Farm-fresh red tomatoes, ideal for cooking',
        price: 35,
        image: 'https://images.unsplash.com/photo-1546470427-227c7369a9b0?w=400',
        category: 'fruits-vegetables',
        stock: 200,
        isAvailable: true,
        rating: 4.3,
        unit: '500g',
    },
    {
        id: 'p4',
        name: 'Green Spinach Bundle',
        description: 'Fresh organic spinach, rich in iron and vitamins',
        price: 25,
        image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400',
        category: 'fruits-vegetables',
        stock: 60,
        isAvailable: true,
        isNew: true,
        rating: 4.4,
        unit: '1 bundle',
    },
    {
        id: 'p5',
        name: 'Amul Butter',
        description: 'Creamy and delicious Amul butter for your bread',
        price: 56,
        image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=400',
        category: 'dairy-breakfast',
        stock: 100,
        isAvailable: true,
        rating: 4.8,
        unit: '100g',
    },
    {
        id: 'p6',
        name: 'Fresh Milk (Full Cream)',
        description: 'Farm fresh full cream milk, pasteurized for safety',
        price: 68,
        image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400',
        category: 'dairy-breakfast',
        stock: 50,
        isAvailable: true,
        rating: 4.6,
        unit: '1 litre',
    },
    {
        id: 'p7',
        name: 'Brown Eggs (6 pack)',
        description: 'Farm-fresh brown eggs, rich in protein',
        price: 72,
        originalPrice: 85,
        image: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=400',
        category: 'dairy-breakfast',
        stock: 40,
        isAvailable: true,
        discount: 15,
        rating: 4.5,
        unit: '6 pcs',
    },
    {
        id: 'p8',
        name: 'Greek Yogurt',
        description: 'Creamy Greek yogurt, high in protein, low in fat',
        price: 120,
        image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
        category: 'dairy-breakfast',
        stock: 35,
        isAvailable: true,
        isNew: true,
        rating: 4.7,
        unit: '400g',
    },
    {
        id: 'p9',
        name: 'Lays Classic Salted',
        description: 'Crispy and delicious classic salted potato chips',
        price: 20,
        image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=400',
        category: 'snacks-beverages',
        stock: 200,
        isAvailable: true,
        rating: 4.2,
        unit: '52g',
    },
    {
        id: 'p10',
        name: 'Coca-Cola',
        description: 'Refreshing Coca-Cola, chilled perfection',
        price: 40,
        image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=400',
        category: 'snacks-beverages',
        stock: 150,
        isAvailable: true,
        rating: 4.4,
        unit: '750ml',
    },
    {
        id: 'p11',
        name: 'Oreo Cookies',
        description: 'Delicious chocolate sandwich cookies with cream filling',
        price: 35,
        originalPrice: 45,
        image: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400',
        category: 'snacks-beverages',
        stock: 80,
        isAvailable: true,
        discount: 22,
        rating: 4.6,
        unit: '120g',
    },
    {
        id: 'p12',
        name: 'Green Tea (25 bags)',
        description: 'Premium green tea for a healthy lifestyle',
        price: 150,
        image: 'https://images.unsplash.com/photo-1556881286-fc6915169721?w=400',
        category: 'snacks-beverages',
        stock: 45,
        isAvailable: true,
        isNew: true,
        rating: 4.5,
        unit: '25 bags',
    },
    {
        id: 'p13',
        name: 'Basmati Rice Premium',
        description: 'Long grain basmati rice, aged for perfect aroma',
        price: 320,
        originalPrice: 380,
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400',
        category: 'staples',
        stock: 60,
        isAvailable: true,
        discount: 16,
        rating: 4.8,
        unit: '5 kg',
    },
    {
        id: 'p14',
        name: 'Whole Wheat Flour',
        description: 'Stone-ground whole wheat flour for healthy rotis',
        price: 180,
        image: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400',
        category: 'staples',
        stock: 75,
        isAvailable: true,
        rating: 4.5,
        unit: '5 kg',
    },
    {
        id: 'p15',
        name: 'Olive Oil Extra Virgin',
        description: 'Premium extra virgin olive oil for cooking and salads',
        price: 450,
        originalPrice: 550,
        image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
        category: 'staples',
        stock: 30,
        isAvailable: true,
        discount: 18,
        rating: 4.7,
        unit: '500ml',
    },
    {
        id: 'p16',
        name: 'Dove Shampoo',
        description: 'Nourishing shampoo for silky smooth hair',
        price: 285,
        originalPrice: 340,
        image: 'https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=400',
        category: 'personal-care',
        stock: 55,
        isAvailable: true,
        discount: 16,
        rating: 4.4,
        unit: '340ml',
    },
    {
        id: 'p17',
        name: 'Colgate MaxFresh',
        description: 'Cooling mint toothpaste for fresh breath',
        price: 95,
        image: 'https://images.unsplash.com/photo-1609840114035-3c981b782dfe?w=400',
        category: 'personal-care',
        stock: 90,
        isAvailable: true,
        rating: 4.3,
        unit: '150g',
    },
    {
        id: 'p18',
        name: 'Nivea Body Lotion',
        description: 'Deep moisturizing lotion for soft, supple skin',
        price: 220,
        image: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
        category: 'personal-care',
        stock: 40,
        isAvailable: true,
        isNew: true,
        rating: 4.6,
        unit: '400ml',
    },
    {
        id: 'p19',
        name: 'Vim Dishwash Gel',
        description: 'Powerful dishwashing gel for sparkling clean dishes',
        price: 125,
        originalPrice: 150,
        image: 'https://images.unsplash.com/photo-1585421514738-01798e348b17?w=400',
        category: 'household',
        stock: 70,
        isAvailable: true,
        discount: 17,
        rating: 4.2,
        unit: '750ml',
    },
    {
        id: 'p20',
        name: 'Surf Excel Matic',
        description: 'Premium detergent for fully automatic washing machines',
        price: 380,
        image: 'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=400',
        category: 'household',
        stock: 45,
        isAvailable: true,
        rating: 4.5,
        unit: '2 kg',
    },
];

const seedData = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI || '');
        console.log('MongoDB Connected for seeding');

        await Product.deleteMany({});
        console.log('Cleared existing products');

        const dbProducts = products.map(p => ({
            name: p.name,
            description: p.description,
            price: p.price,
            original_price: p.originalPrice,
            image: p.image,
            category: p.category,
            stock: p.stock,
            is_available: p.isAvailable,
            is_new: (p as any).isNew || false,
            discount: p.discount || 0,
            rating: p.rating,
            unit: p.unit
        }));

        await Product.insertMany(dbProducts);
        console.log('Products seeded successfully');

        process.exit();
    } catch (error) {
        console.error('Error seeding data:', error);
        process.exit(1);
    }
};

seedData();
